### DISCUSSION TITLE
placement.service constraints?  I understood they are ignored

### DISCUSSION THREAD

**Discussion by francescor** [crazy-max/swarm-cronjob#390] [General]
Did I understood it correctly? any `placement.contraints` defined in a service with label: `swarm.cronjob.enable: 'true'` is totally ignored: what is applied is the `placement.contraints`  of the `swarm-cronjob` itself?

In details:

Once I have swarm-cronjob with contraints to run on `managers` and `arm`, so as the following:

```
services:
  app:
    image: crazymax/swarm-cronjob:1.13
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.platform.arch == aarch64
```

I cannot use the following to run the cronjob in `x86` nodes and in `workers`

```
  my_service:
    image: my_image
    deploy:
      mode: replicated
      replicas: 0
      labels:
        swarm.cronjob.enable: 'true'
        swarm.cronjob.schedule: '17 */6 * * *'
        swarm.cronjob.skip-running: 'true'
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == manager
          - node.platform.arch == x86_64
 ```
 
 since this latter `placement.constraints` is ignored
