### ISSUE TITLE
docker cap_add seems to work only with replica to 1 and not in scheduled mode

### ISSUE THREAD

**Issue by NicolasLeCorre** [crazy-max/swarm-cronjob#175]
Hi, and thanks for your work !

We use cronjob to start jobs in our clusters and for some reasons we need for one of our container to set the mac_address (licensing stuff). We found that adding cap_add: - NET_ADMIN allow us to override that value and we are ok with that.

We then tried to deploy such a container in our swarm and found that :
* if the container is started with deploy: replica: 1, it is running well
* if the container is started by the scheduler : swarm.cronjob.schedule=* * * * * for example, we see the error : ip: ioctl 0x8914 failed: Operation not permitted

In the docker documentation, we can see that :
`Note when using docker stack deploy

The cap_add and cap_drop options are ignored when [deploying a stack in swarm mode](https://docs.docker.com/engine/reference/commandline/stack_deploy/)`

But it seems that with our used version of docker (20.10.10) and cronjob (1.10.0, latest) the cap_add is NOT ignored, or at least for the replica :1 option.

Here is an example of our iml file :
`version: '3.8'

services:
  stream:
    image: alpine
    entrypoint: [ "/bin/sh","-c" ]
    command: >
        "ip link set dev eth0 down
        && ip link set dev eth0 address fa:16:3e:87:02:d7
        && ip link set dev eth0 up"
    deploy:
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=* * * * *"
        - "swarm.cronjob.skip-running=true"
    cap_add:
      - NET_ADMIN`

**Comment by crazy-max** [comment]
Apparently capabilities are not handled for swarm services. In #203 I have added a new label `swarm.cronjob.capabilities` where we can set kernel capabilities when the service is updated but does not seem to work:

```yaml
# cap.yml
version: "3.8"

services:
  test:
    image: alpine:edge
    command: >
      /bin/sh -c "apk add libcap-utils && capsh --print | grep Current: | cut -d' ' -f2"
    deploy:
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=*/5 * * * * *"
        - "swarm.cronjob.skip-running=true"
        - "swarm.cronjob.capabilities=NET_ADMIN"
    cap_add:
      - NET_ADMIN
```

```console
$ docker service logs cap_test
cap_test.1.yll3wwu5g846@fv-az74-398    | fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
cap_test.1.yll3wwu5g846@fv-az74-398    | fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
cap_test.1.yll3wwu5g846@fv-az74-398    | (1/2) Installing libcap2 (2.64-r1)
cap_test.1.yll3wwu5g846@fv-az74-398    | (2/2) Installing libcap-utils (2.64-r1)
cap_test.1.yll3wwu5g846@fv-az74-398    | Executing busybox-1.35.0-r18.trigger
cap_test.1.yll3wwu5g846@fv-az74-398    | OK: 6 MiB in 16 packages
cap_test.1.yll3wwu5g846@fv-az74-398    | cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap=ep
```

Also looking at the docs it seems it's not supported when deploying a stack in swarm mode: https://docs.docker.com/compose/compose-file/compose-file-v3/#cap_add-cap_drop

I'm not sure why it works with `replicas: 1` though.
