### ISSUE TITLE
Non-cronjob containers are added to cronjob list

### ISSUE THREAD

**Issue by acehege** [crazy-max/swarm-cronjob#2]
### Behaviour
swarm-cronjob adds non-crontab services to crontab schedule, 

#### Steps to reproduce this issue

1. Deploy swarm-cronjob following the Quickstart guide.

2. Deploy service with crontab labels

3. Verify that the service is picked up by swarm-cronjob

4. Deploy service without the swarm-cronjob specified labels

#### Expected behaviour

> Only services with the required labels should be picked up by swarm-cronjob 

#### Actual behaviour

> Services without the required labels are picked up and added without a schedule by swarm-cronjob

### Configuration

* Target Docker version (the host/cluster you manage) : 17.06.2-ee-16
* Platform (windows/linux) : linux
* Target Swarm version : 17.06.2-ee-16

### Docker info

> Containers: 26
 Running: 13
 Paused: 0
 Stopped: 13
Images: 843
Server Version: 17.06.2-ee-16
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: iesbyog0ek52azwt02v9y3hrc
 Is Manager: true
 ClusterID: 26uqxgbgutp9acw2v4ntxma8f
 Managers: 3
 Nodes: 22
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
  External CAs:
    cfssl: https://10.107.XXX.186:12381/api/v1/cfssl/sign
    cfssl: https://10.107.XXX.184:12381/api/v1/cfssl/sign
    cfssl: https://10.107.XXX.185:12381/api/v1/cfssl/sign
 Root Rotation In Progress: false
 Node Address: 10.107.XXX.186
 Manager Addresses:
  10.107.XXX.184:2377
  10.107.XXX.185:2377
  10.107.XXX.186:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 462c82662200a17ee39e74692f536067a3576a50
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-133-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.65GiB
Name: XXX
ID: VF5U:RKYW:353Q:5TIJ:5I2H:FTZA:FQCH:XXXX:HHM7:KLKE:WPPF:CLGI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 152
 Goroutines: 327
 System Time: 2019-01-11T10:58:05.751575781+01:00
 EventsListeners: 9
Http Proxy: XXX
Https Proxy: XXX
No Proxy: localhost,127.0.0.0/8,XXX
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Logs

> Service logs (set LOG_LEVEL to debug)

```
Thu, 10 Jan 2019 17:34:10 CET INF Add cronjob for service shared_runner_runner with schedule 
Thu, 10 Jan 2019 17:34:10 CET ERR Cannot update job for service shared_runner_runner error="Empty spec string"
Thu, 10 Jan 2019 17:34:10 CET INF Add cronjob for service shared_runner_runner with schedule 
Thu, 10 Jan 2019 17:34:10 CET ERR Cannot update job for service shared_runner_runner error="Empty spec string"
Thu, 10 Jan 2019 17:34:41 CET INF Add cronjob for service shared_runner_runner with schedule 
Thu, 10 Jan 2019 17:34:41 CET ERR Cannot update job for service shared_runner_runner error="Empty spec string"
```

**Comment by crazy-max** [comment]
Hi @acehege, can you post your compose files ?

**Comment by acehege** [comment]
> Hi @acehege, can you post your compose files ?

Sure...
## non-crontab service
```
version: '3.6'
services:
    runner:
        build:
            context: .
        image: $DOCKER_REGISTRY_REPO:$DOCKER_TAG
        environment:
            - RUNNER_TAG_LIST
            - RUNNER_EXECUTOR=${RUNNER_EXECUTOR-shell}
            - REGISTER_RUN_UNTAGGED=${REGISTER_RUN_UNTAGGED-false}
            - DOCKER_IMAGE
        command: run
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/gitlab_runner_builds:/opt/gitlab_runner_builds
        deploy:
            replicas: 1
            update_config:
                order: start-first
            placement:
                constraints:
                    - node.role == manager
```

No extra labels are added to the service other then the default ones:

```
                "com.docker.stack.image": "XXX/infrastructure/gitlab-runner-with-docker:fa9c1fd",
                "com.docker.stack.namespace": "shared_runner",
                "com.docker.ucp.access.label": "/",
                "com.docker.ucp.collection": "swarm",
                "com.docker.ucp.collection.root": "true",
                "com.docker.ucp.collection.swarm": "true"
```
## crontab enabled service

```
version: '3.7'

x-cron-labels:
  &default-cron-labels
  swarm.cronjob.enable: "true"
  swarm.cronjob.schedule: "${SERVICE_CRONTAB_SCHEDULE:?err}"
  swarm.cronjob.skip-running: "false"

services:
  app:
    healthcheck:
      test: ["NONE"]
    labels:
      << : *default-cron-labels
    deploy:
      labels:
        << : *default-cron-labels
      restart_policy:
        condition: none
```
