### ISSUE TITLE
cron doesnt work in swarm

### ISSUE THREAD

**Issue by batchenr** [crazy-max/swarm-cronjob#25]
### Behaviour

Im using docker 19.03.5 and compose version 1.25.0
I did test this on docker-compose with no swarm and it works, once i deploy on swarm
it doesnt matter what i put in the swarm.cronjob.schedule  swarm start container with a script, and when the script end container stops - every 10 seconds.

i want the container to go up every X time that i have set in ""swarm.cronjob.schedule".
here is my settings:

```
        cron:
                image: crazymax/swarm-cronjob:latest
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                environment:
                        - "TZ=Asia/Jerusalem"
                        - "LOG_LEVEL=debug"
                        - "LOG_JSON=false"
                deploy:
                   placement:
                     constraints:
                        - node.role == manager

        service1:
                image: 127.0.0.1:5000/api2:latest
                command: python session.py
                labels:
                        - "swarm.cronjob.enable=true"
                        - "swarm.cronjob.schedule=0/30 * * * * *"
                        - "swarm.cronjob.skip-running=true"
                deploy:
                   placement:
                     constraints:
                        - node.role == manager

```

I have a swarm with only one host at the time ( meaning a swarm of 1 machine which is the manager) i will excpent it later.

i use ubuntu 18

logs from cron container:
```

base_cron.1.2y0btqbrsewm@ansible    | Mon, 27 Jan 2020 11:18:44 IST DBG Event triggered newstate=completed oldstate=updating service=base_service1
base_cron.1.2y0btqbrsewm@ansible    | Mon, 27 Jan 2020 11:18:44 IST DBG Cronjob disabled service=base_service1

```

What am i doing wrong ?
