### ISSUE TITLE
How to pass variables to run docker commands

### ISSUE THREAD

**Issue by bd8392** [crazy-max/swarm-cronjob#33]
Hi =)

I've a problem...I've a nextcloud instance running in swarm, that needs a cronjob...I can't figure out how to set this...my approach was the following: 

```
version: '3.3'
services:
  cron:
    image: crazymax/swarm-cronjob:latest
    environment:
      LOG_JSON: 'false'
      LOG_LEVEL: info
      TZ: Europe/Vienna
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == manager
  nextcloud_cron_php:
    image: docker:latest
    command: docker exec --user www-data $(docker ps -q -f name=nextcloud_stack_nextcloud) php -f /var/www/html/cron.php
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      mode: global
      labels:
        swarm.cronjob.enable: 'true'
        swarm.cronjob.schedule: '* * * * *'
        swarm.cronjob.skip-running: 'false'
      restart_policy:
        condition: none
networks:
  default:
    driver: overlay
```
The command works in docker run, but it doesn't work in the compose-style (the $(docker ps -q -f name=nextcloud_stack_nextcloud) part is missinterpreted). Can someoene help set this up correctly?

Besides thanks for all the cool containers and development crazymax =)

**Comment by bd8392** [comment]
Still didn't figure out what I'm doing wrong... anyone an idea? I'm using rancher-os so this system has no local cron...

**Comment by bd8392** [comment]
Ok I made multiple tries now... didn't get it to work...the part $(docker ps -q -f name=nextcloud_stack_nextcloud) is always missunderstood by docker compose yml (swarm)

**Comment by crazy-max** [comment]
Hi @bd8392 

Compose cannot interpret commands. See docker/compose#4081.

**Comment by bd8392** [comment]
Okay thanks for the help :-) do you have an idea how I can execute the command on my nextcloud service with your solution? It's the only for swarm and rancheros I think...

**Comment by crazy-max** [comment]
@bd8392 Take a look at my [swarm stack for Matomo](https://github.com/crazy-max/docker-matomo/tree/master/examples/swarm), it's pretty similar.

**Comment by bd8392** [comment]
Oh thanks! =) I'm totally sorry I completely overlooked that...But I've a question on this:
I'm running ouroboros (automatic stack updater to update my nextcloud). Whaht happens, if the production-container and the cron container versions differ? can this break my setup when the diffference would be only for one or two runtimes of the job (becuse the cron-contianer get's updated to)?

**Comment by bd8392** [comment]
I tried it out meanwhile and your solution works perfectly! Thanks =)))

**Comment by bd8392** [comment]
Hi =) I wanted to provide some examples for webcron for your docs as a small thank you for your development =)

Here is a webcron-example for nectcloud (with encrypted swarm network):
```
version: '3.3'
services:
  cron:
    image: crazymax/swarm-cronjob:latest
    environment:
      LOG_JSON: 'true'
      LOG_LEVEL: info
      TZ: Europe/Vienna
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == manager
  nextcloud_cron_webcron:
    image: curlimages/curl:latest
    command:
     - curl
     - https://domain.nextcloud.own/cron.php
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      mode: global
      labels:
        swarm.cronjob.enable: 'true'
        swarm.cronjob.schedule: '*/5 * * * *'
        swarm.cronjob.skip-running: 'false'
      restart_policy:
        condition: none
networks:
  default:
    driver: overlay
    driver_opts:
      opt: encrypted
```
If you want to use another webcron, just replace the url (for example for matomo). With this solution, you don't have to put volumes in your config, and don't have to worry about updating =)
