### ISSUE TITLE
TZ Issue like crazy-max/diun#1131

### ISSUE THREAD

**Issue by fl4shback** [crazy-max/swarm-cronjob#335]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/swarm-cronjob/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Just like https://github.com/crazy-max/diun/issues/1131 this container is affected by the TZ issue from go.
I can't set it to the right TZ anymore.

### Expected behaviour

TZ env var should set the correct TZ in container.

### Actual behaviour

It doesn't

### Steps to reproduce

1. Set TZ
2. Date command in shell returns wrong date

### swarm-cronjob version

latest

### Docker info

```text
/
```

### Docker Compose config

```yaml
services:
  swarm-cronjob:
    deploy:
      placement:
        constraints:
          - node.labels.device==pi
    image: crazymax/swarm-cronjob
    networks:
      - adv_backend
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - "TZ=Europe/Paris"

networks:
  adv_backend:
    name: adv_backend
    driver: overlay
    attachable: true
```

### Logs

```text
/
```
