### ISSUE TITLE
Healthcheck endpoint ?

### ISSUE THREAD

**Issue by pascalandy** [crazy-max/swarm-cronjob#368]
### Description

using docker stack, I would like to do:

```yml
  scheduler:
    image: crazymax/swarm-cronjob:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "TZ=America/Toronto"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      update_config:
        order: start-first
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
```
