### ISSUE TITLE
Skip-running not working on a 3-nodes cluster

### ISSUE THREAD

**Issue by axel-marbois** [crazy-max/swarm-cronjob#4]
# Behaviour

Hi, 

First of all, thank you so much for this awesome repo. I just unfortunately noticed that the "skip-running" argument does not work on my 3-nodes swarm cluster.
It works correctly once, then it begins to shutdown and re-run running services.

## Steps to reproduce this issue

Here is my docker-compose : 
```
version: "3.6"
services:
  # Swarm cronjob
  swarm-cronjob:
    image: crazymax/swarm-cronjob:1.1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=info
      - LOG_JSON=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  sleep:
    image: busybox
    command: sleep 58
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=0/10 * * * * * # each ten secs
        - swarm.cronjob.skip-running=true # but only each minut with this
```

## Expected behaviour

A single service completed each minut.

## Actual behaviour

Here is the docker service logs test-cron_swarm-cronjob -f output : 
```
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"info","time":"2019-04-25T13:51:40Z","message":"Start test-cron_sleep (exit 0 ; complete)"}
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"info","time":"2019-04-25T13:51:50Z","message":"Start test-cron_sleep (exit 0 ; complete)"}
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"info","time":"2019-04-25T13:52:00Z","message":"Start test-cron_sleep (exit 0 ; complete)"}
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"info","time":"2019-04-25T13:52:10Z","message":"Start test-cron_sleep (exit 1 ; ready)"}
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"info","time":"2019-04-25T13:52:20Z","message":"Start test-cron_sleep (exit 1 ; shutdown)"}
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"info","time":"2019-04-25T13:52:30Z","message":"Start test-cron_sleep (exit 1 ; shutdown)"}
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"info","time":"2019-04-25T13:52:40Z","message":"Start test-cron_sleep (exit 1 ; shutdown)"}
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"warn","time":"2019-04-25T13:52:50Z","message":"Skip test-cron_sleep (exit 1 ; running)"}
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"info","time":"2019-04-25T13:53:00Z","message":"Start test-cron_sleep (exit 1 ; shutdown)"}
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"info","time":"2019-04-25T13:53:10Z","message":"Start test-cron_sleep (exit 1 ; ready)"}
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"info","time":"2019-04-25T13:53:20Z","message":"Start test-cron_sleep (exit 1 ; shutdown)"}
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"info","time":"2019-04-25T13:53:30Z","message":"Start test-cron_sleep (exit 1 ; shutdown)"}
test-cron_swarm-cronjob.1.qrvfjoycbnhv@devdock2    | {"level":"info","time":"2019-04-25T13:53:40Z","message":"Start test-cron_sleep (exit 1 ; shutdown)"}
```

Here is the docker service ps --no-trunc test-cron_sleep output : 
```
Every 5.0s: docker service ps --no-trunc test-cron_sleep            devdock1: Thu Apr 25 15:53:19 2019

ID                          NAME                    IMAGE
                                    NODE                DESIRED STATE       CURRENT STATE             ERR
OR               PORTS
qoe1htr8tjywa3wovlziqa8wf   test-cron_sleep.1       busybox:latest@sha256:954e1f01e80ce09d0887ff6ea10b13a
812cb01932a0781d6b0cc23f743a874fd   devdock1         Running             Running 6 seconds ago

8wy308c7tx6t7hokeh03j8zzq    \_ test-cron_sleep.1   busybox:latest@sha256:954e1f01e80ce09d0887ff6ea10b13a
812cb01932a0781d6b0cc23f743a874fd   devdock1         Shutdown            Shutdown 7 seconds ago

w1cj0nz1arzn1vedzrrexdmc0    \_ test-cron_sleep.1   busybox:latest@sha256:954e1f01e80ce09d0887ff6ea10b13a
812cb01932a0781d6b0cc23f743a874fd   devdock1         Shutdown            Shutdown 5 seconds ago

j0lol5la1683ar1oquh6khggp    \_ test-cron_sleep.1   busybox:latest@sha256:954e1f01e80ce09d0887ff6ea10b13a
812cb01932a0781d6b0cc23f743a874fd   devdock1         Shutdown            Shutdown 25 seconds ago

w8wo5al2ynfxbw839lkbsfi4w    \_ test-cron_sleep.1   busybox:latest@sha256:954e1f01e80ce09d0887ff6ea10b13a
812cb01932a0781d6b0cc23f743a874fd   devdock1         Shutdown            Shutdown 45 seconds ago
```

The cronjob seems to consider the job as complete and rerun it many times, but he is still running at this moment. 

I checked your portion of code managing this (it seems to be the worker.go) but I didn't find any obvious. This may also come from my own swarm configuration. Can you reproduce this bug ?

# Configuration

Docker version : 18.09.2, build 6247962

# Logs

Detailed earlier

Thank you a lot,

Axel
