### ISSUE TITLE
cronjob for an existing service in swarm

### ISSUE THREAD

**Issue by ne0c0de** [crazy-max/swarm-cronjob#5]
Hi,

I have a service in my swarm that is running my nodejs application and my goal is creating a crontab task inside of it. So if I put command lines to swarm configuration it's overlapsing my docker image command and my service doesn't run.

So how can i configure it? Also how can i run multiple commands? (such as every minute, every hour etc.)

**Comment by crazy-max** [comment]
Hi @ne0c0de,

I am not sure I understood your request. swarm-cronjob already takes care of calling services but they must meet the prerequisites [explained in the README](https://github.com/crazy-max/swarm-cronjob#swarm-cluster). You can find some examples [here](https://github.com/crazy-max/swarm-cronjob/tree/master/.res/example).

Can you give more detailed explanations with a use case by posting your compose file ?

**Comment by ne0c0de** [comment]
Hello @crazy-max 

thank you for fast response

here's my swarm config:

```
version: '3'
services:
  traefik:
    image: traefik
    command:
      - --web
      - --docker
      - --docker.domain=docker.localhost
      - --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    depends_on:
      - myapp
  myapp:
#    build: .
    image: hardc0der/myapp:latest
    labels:
      - "traefik.port=3003"
      - "traefik.backend=webserver"
      - "traefik.frontend.rule=Host:app.myapp.co"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ~/Development/monai:/usr/src/app
      - ~/myapp/config:/usr/src/app/config
      - ~/myapp/log:/usr/src/app/log
      - ~/myapp/log:/usr/src/log
      - ~/myapp/images:/usr/src/app/client/images
    links:
      - mongodb
    depends_on:
      - mongodb
#    ports:
#      - "3003:3003"
    restart: unless-stopped
    command: node /usr/src/app/test.js > /usr/src/app/log/curl.log
    deploy:
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 * * * * *"
        - "swarm.cronjob.skip-running=false"
      replicas: 0
      restart_policy:
        condition: none
  crontab:
    image: crazymax/swarm-cronjob
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Istanbul"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      placement:
        constraints:
          - node.role == manager
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
    ports:
      - "27017:27017"
    volumes:
      - mongoData:/data/db
volumes:
  mongoData:
    driver: local
  myapp:
```

i want to run 

```
node /usr/src/app/test.js > /usr/src/app/log/curl.log
```

command on myapp container in every minutes (also i have another commands that i want to run on same container.

This is my aim but i couldn't achieved yet. I were did it with ofelia when i used docker-compose but ofelia doesn't work with swarm because of container name couldn't be reached.
