### ISSUE TITLE
Swarm-cronjob to stop/start services ?

### ISSUE THREAD

**Issue by Akaori** [crazy-max/swarm-cronjob#77]
Hi,

I would like to know if it is possible to use swarm-cronjob to stop running services running in containers and start other containers ?

Supposing I have limited resources on the cloud, and both Flask app and Airflow tasks should not be running at the same time.

Can I use swarm-cronjob to accomplish it (Schedule what time each container should be running / be able to stop one container before starting another) ?

**Comment by panasenco** [comment]
I just had the same problem. Adding the below to my docker-compose file (along with swarm-cronjob of course) allows me to start and stop a service at certain times of day every day:

```
  my_service_starter:
    image: docker
    command: ["docker", "service", "scale", "my_service=9"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 9 * * *"
      restart_policy:
        condition: none

  my_service_stopper:
    image: docker
    command: ["docker", "service", "scale", "my_service=0"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=00 23 * * *"
      restart_policy:
        condition: none
```
